---
title: "Aquarium Temps"
author: "Will Ruman"
output: html_document
date: "`r Sys.Date()`"
params:
  infile: "~/Documents/temp.log"
---

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("tidyverse")
library("lubridate")
library("ggplot2")
```

# Load Data
```{r load, message=FALSE}
temps <- read_tsv(path.expand(params$infile), col_names = c("Time", "Reading"))

temps$Celsius <- temps$Reading / 1000
temps$Fahrenheit <- (temps$Celsius * 1.8) + 32
```

# Temperature Over Time
Temperature samples over the data collection period.

```{r overtime}
ggplot(temps) +
  geom_point(aes(x = Time, y = Fahrenheit, color = Fahrenheit)) +
  scale_x_datetime(date_breaks = "7 days", guide = guide_axis(n.dodge = 2))
```

# Temperature Distribution by Time of Day
What temperature ranges describe each part of the day? 

```{r bypartofday}
temps_with_time_of_day <- temps %>%
	mutate(TimeOfDay = case_when(
		hour(Time) >= 20 | hour(Time) <= 5 ~ 'Night'
		, hour(Time) > 5 & hour(Time) < 12 ~ 'Morning'
		, hour(Time) >= 12 & hour(Time) < 20 ~ 'Afternoon'
	))

ggplot(temps_with_time_of_day) +
  geom_density(aes(x = Fahrenheit, fill = TimeOfDay), alpha = 0.4)
```

# Temperature Distribution by Day
What temperature ranges describe each day of the week?

```{r byday}
ggplot(temps) +
  geom_density(aes(x = Fahrenheit, fill = weekdays(Time)), alpha = 0.4)
```

# Temperature Stats by Day
Boxplots showing vital statistics by day of the week.

```{r bydaybox}
ggplot(temps) +
  geom_boxplot(aes(x = weekdays(Time), y = Fahrenheit))

```
